udpdate

diff --git a/.github/workflows/matrix.yml b/.github/workflows/matrix.yml
--- a/.github/workflows/matrix.yml
+++ b/.github/workflows/matrix.yml
@@ -16,6 +16,7 @@ jobs:
     runs-on: ${{ matrix.os}}
 
     strategy:
+      fail-fast: false
       matrix:
         python-version: ["3.10", "3.11", "3.12"]
         os: [ubuntu-latest, windows-latest]
@@ -37,3 +38,9 @@ jobs:
           echo "Operating System: ${{ runner.os }}"
           echo "Runner: ${{ matrix.os }}"
           echo "Python version: ${{ matrix.python-version }}"
+
+      - name: Simulate failure
+        if: matrix.os == ' windows-latest ' && matrix.python-verson == '3.10'
+        run: |
+          echo "This job is failing intentionally!"
+          exit 1
