Update matrix.yml

diff --git a/.github/workflows/matrix.yml b/.github/workflows/matrix.yml
--- a/.github/workflows/matrix.yml
+++ b/.github/workflows/matrix.yml
@@ -39,8 +39,8 @@ jobs:
           echo "Runner: ${{ matrix.os }}"
           echo "Python version: ${{ matrix.python-version }}"
 
-      - name: Simulate failure
-        if: matrix.os == 'windows-latest' && matrix.python-version == '3.10'
-        run: |
-          echo "This job is failing intentionally!"
-          exit 1
+      # - name: Simulate failure
+      #   if: matrix.os == 'windows-latest' && matrix.python-version == '3.10'
+      #   run: |
+      #     echo "This job is failing intentionally!"
+      #     exit 1
